name: Build APK (legacy)

on:
  workflow_dispatch:
  push:
    paths:
      - 'app/**'
      - 'build.gradle'
      - 'settings.gradle'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
      - name: Accept SDK Licenses
        run: yes | sdkmanager --licenses
      - name: Install build tools and platform
        run: sdkmanager "platforms;android-23" "build-tools;23.0.3" "platform-tools"
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: LeopardMediaHD-debug-apk
          path: app/build/outputs/apk/debug/*.apk
